### ISSUE TITLE
copy logging/options/syslog-address properties

### ISSUE THREAD

**Issue by jzaefferer** [sloppyio/sloppose#10]
No mapping needed, since this is using the docker-compose format already:

```
logging:
  options:
    syslog-address: "udp://YourHost.papertrailapp.com:123"
```

See https://docs.docker.com/compose/compose-file/#logging and https://kb.sloppy.io/features/sloppy-yaml-reference/115-external-logging-yaml

**Comment by malud** [comment]
Whats the point here?

this can be read as copy: https://github.com/sloppyio/sloppose/blob/master/pkg/converter/sloppy_file.go#L89

**Comment by jzaefferer** [comment]
Okay, already implemented
