### ISSUE TITLE
Replace compose file library

### ISSUE THREAD

**Issue by kevinsandow** [sloppyio/sloppose#15]
Currently in use (but no longer maintained):
* `github.com/aanand/compose-file/loader` 
* `github.com/aanand/compose-file/types`

Should be replace with:
* `github.com/docker/cli/cli/compose/loader`
* `github.com/docker/cli/cli/compose/types`

**Comment by jzaefferer** [comment]
Is that a matter of replacing the package name, or do these have different APIs? An estimate would be great.

**Comment by kevinsandow** [comment]
I took a quick look at it, and unfortunately there are a couple of different interfaces... 
I will have to ask @malud why he choose the old library and also the experimental https://github.com/docker/libcompose
