### ISSUE TITLE
add documentation for limitations

### ISSUE THREAD

**Issue by malud** [sloppyio/sloppose#2]
Since there are some implicit behaviours during docker-compose.yml conversion it should be written down as little guide for docker-compose file requirements which have to be fulfilled for a seamless conversion.

**Comment by jzaefferer** [comment]
Not supported: health checks

See https://docs.docker.com/compose/compose-file/#healthcheck and https://kb.sloppy.io/features/health-checks

**Comment by jzaefferer** [comment]
Will address this ad-hoc as we run into limitations in practice...
