### ISSUE TITLE
implementation for resource mapping

### ISSUE THREAD

**Issue by malud** [sloppyio/sloppose#3]
We should support the conversion for memory limits, cpu utilization and deployment settings/scaling(v3).

V2: https://docs.docker.com/compose/compose-file/compose-file-v2/#cpu_count-cpu_percent-cpu_shares-cpu_quota-cpus-cpuset-domainname-hostname-ipc-mac_address-mem_limit-memswap_limit-mem_swappiness-mem_reservation-oom_score_adj-privileged-read_only-shm_size-stdin_open-tty-user-working_dir

V3: https://docs.docker.com/compose/compose-file/#deploy

**Comment by jzaefferer** [comment]
Replaced by #7
