### ISSUE TITLE
Recognize '3.1' as a valid version

### ISSUE THREAD

**Issue by jzaefferer** [sloppyio/sloppose#6]
Given `version: '3.1'` (from https://hub.docker.com/_/wordpress/), the input is rejected with "Error: missing version declaration in compose file".

**Comment by malud** [comment]
Since the underlying package `https://github.com/aanand/compose-file` doesn't support 3.1 and above compose versions (https://docs.docker.com/compose/compose-file/compose-versioning/) we doesn't either and this would be a feature request. At least within the compose-file package.

**Comment by jzaefferer** [comment]
Fixed by #12 - now it properly rejects 3.1, instead of failing to recognize the version altogether.
